### ISSUE TITLE
你好，请问怎么登陆b站？

### ISSUE THREAD

**Issue by fengyuanluo** [gaoxiaoduan/YoutubeToBilibiliHelp#12]
如题，试了win和无桌面版的linux，找不到怎么登陆，还是说cookie.json要自己创建？谢谢

**Comment by gaoxiaoduan** [comment]
终端里会有一个二维码，用b站扫码登录就好

**Comment by fengyuanluo** [comment]
> 终端里会有一个二维码，用b站扫码登录就好

你好，我windows端测试用的是模版upload.config.json文件，运行程序之后直接就开始下载了，docker端也是，在portainer里的日志如下，两个都未出现二维码。
2024-02-24T08:48:31: PM2 log: Launching in no daemon mode
2024-02-24T08:48:31: PM2 log: App [ytToX:0] starting in -cluster mode-
2024-02-24T08:48:32: PM2 log: App [ytToX:0] online
02-24 08:48:34: 项目启动～🚀
02-24 08:48:34: 当前环境为：正式环境
02-24 08:48:34: 根据自定义时间获取视频
02-24 08:48:34: command https://www.youtube.com/@addyvisuals/videos --proxy "" --dateafter 20230226 --datebefore 20240224 --skip-download --print-json
02-24 08:48:34: 开始获取指定日期范围的视频
02-24 08:48:34: 若用户的视频较多,需要挨个查看,失败请重试～请耐心等待...
02-24 08:49:18: 获取指定日期范围的视频成功,共4条视频
02-24 08:49:18: 发现频道有更新 --> Addy Visuals:Redesigning Spotify (Concept) [https://www.youtube.com/watch?v=cFlnpWs4cLU]
02-24 08:49:18: -----[字幕]阶段开始-----
02-24 08:49:18: 下载命令： https://www.youtube.com/watch?v=cFlnpWs4cLU --proxy  --write-auto-sub --write-sub --sub-lang en,zh-Hans,zh-Hans-en --sub-format vtt --skip-download -o /usr/app/videos/Addy Visuals/2024_02_24__cFlnpWs4cLU.%(ext)s
02-24 08:49:22: 字幕下载完毕～
02-24 08:49:22: -----[字幕]阶段结束-----
02-24 08:49:22: -----[视频]阶段开始-----
02-24 08:49:22: 下载命令： https://www.youtube.com/watch?v=cFlnpWs4cLU --proxy  -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 --write-thumbnail -o /usr/app/videos/Addy Visuals/2024_02_24__cFlnpWs4cLU.%(ext)s
02-24 08:49:29: 视频下载完毕～
02-24 08:49:29: -----[视频]阶段结束-----
02-24 08:49:29: -----封面格式转换阶段开始-----
02-24 08:49:30: -----加字幕阶段开始-----
02-24 08:49:30: processVideo: /usr/app/videos/Addy Visuals 2024_02_24__cFlnpWs4cLU
2024-02-24T08:50:10: PM2 log: Stopping app:ytToX id:0
2024-02-24T08:50:11: PM2 log: App name:ytToX id:0 disconnected
2024-02-24T08:50:11: PM2 log: App [ytToX:0] exited with code [0] via signal [SIGINT]
2024-02-24T08:50:11: PM2 log: pid=18 msg=process killed
2024-02-24T08:50:11: PM2 log: PM2 successfully stopped
2024-02-24T09:20:58: PM2 log: Launching in no daemon mode
2024-02-24T09:20:58: PM2 log: App [ytToX:0] starting in -cluster mode-
2024-02-24T09:20:58: PM2 log: App [ytToX:0] online
02-24 09:21:00: 项目启动～🚀
02-24 09:21:00: 当前环境为：正式环境
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getConfigFile (file:///usr/app/dist/utils/files.js:23:25)
    at main (file:///usr/app/dist/index.js:14:20)
    at file:///usr/app/dist/index.js:38:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15)

**Comment by fengyuanluo** [comment]
docker端重新跑了一次构建程序好了，感谢大大，请问可以直接订阅像music或者gaming这种频道吗？

**Comment by gaoxiaoduan** [comment]
@fengyuanluo 目前不行，没做这块的功能
