### ISSUE TITLE
error

### ISSUE THREAD

**Issue by whooooo589** [gaoxiaoduan/YoutubeToBilibiliHelp#7]
Error: Failed to launch the browser process!
/root/.cache/puppeteer/chrome/linux-115.0.5790.102/chrome-linux64/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

**Comment by whooooo589** [comment]
我尝试将upload.ts内的header注释后dev模式启动，但是没有用

**Comment by gaoxiaoduan** [comment]
重新build了吗？改代码后需要build一下再执行

**Comment by whooooo589** [comment]
> 重新build了吗？改代码后需要build一下再执行

build了

**Comment by gaoxiaoduan** [comment]
把`puppeteer `删掉后重新跑一下，docker版本已经出了，可以使用docker运行项目了，不同平台之间的报错问题，不好复现

**Comment by whooooo589** [comment]
> 把`puppeteer `删掉后重新跑一下，docker版本已经出了，可以使用docker运行项目了，不同平台之间的报错问题，不好复现

08-14 05:48:01: failed to fetch global config MaxRedirectsError: Redirected 10 times. Aborting.
    at Request._onResponseBase (/usr/app/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:859:35)
    at Request._onResponse (/usr/app/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:948:24)
    at ClientRequest.<anonymous> (/usr/app/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:962:23)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:526:35)
    at origin.emit (/usr/app/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:541:22)
    at TLSSocket.emit (node:events:514:28) {
  code: 'ERR_TOO_MANY_REDIRECTS',
  timings: undefined
}
